//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9151
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenFoodFactsClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenFoodFactsClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;code&quot;: &quot;0737628064502&quot;,
        ///  &quot;status&quot;: 1,
        ///  &quot;status_verbose&quot;: &quot;product found&quot;,
        ///  &quot;product&quot;: {
        ///    &quot;languages_hierarchy&quot;: [
        ///      &quot;en:english&quot;
        ///    ],
        ///    &quot;expiration_date_debug_tags&quot;: [],
        ///    &quot;states_hierarchy&quot;: [
        ///      &quot;en:to-be-checked&quot;,
        ///      &quot;en:complete&quot;,
        ///      &quot;en:nutrition-facts-completed&quot;,
        ///      &quot;en:ingredients-completed&quot;,
        ///      &quot;en:expiration-date-to-be-completed&quot;,
        ///      &quot;en:packaging-code-to-be-completed&quot;,
        ///      &quot;en:characteristics-completed&quot;,
        ///      &quot;en:categories-completed&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string product_0737628064502 {
            get {
                return ResourceManager.GetString("product_0737628064502", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap product_image {
            get {
                object obj = ResourceManager.GetObject("product_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://openfoodfacts.pythonanywhere.com/api/product/.
        /// </summary>
        internal static string UrlOpenFoodFactsApi {
            get {
                return ResourceManager.GetString("UrlOpenFoodFactsApi", resourceCulture);
            }
        }
    }
}
